---
- name: Copy wrapper script
  template:
    src: templates/local-ca.sh
    dest: "{{ ca_base_dir }}/local-ca.sh"
    owner: "{{ ca_owner }}"
    group: "{{ ca_group }}"
    mode: 0700

- name: Copy readme templates
  copy:
    src: "files/readme.txt"
    dest: "{{ ca_base_dir }}/readme.txt"
    owner: "{{ ca_owner }}"
    group: "{{ ca_group }}"
    mode: 0644